{% set version = "1.1.0" %}

package:
  name: openfpgaloader
  version: {{ version }}

source:
  url: https://github.com/trabucayre/openFPGALoader/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d2d3da194e3e578ce81f1156f85c128eb6021b73b0c67bbeec9cd5d8bea35fda

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - pkg-config
    - cmake
    - make
  host:
    - zlib
    - libudev
    - libgpiod
    - libftdi
    - libusb
  run:
    - {{ pin_compatible("libudev") }}
    - {{ pin_compatible("libgpiod") }}
    - {{ pin_compatible("libftdi") }}

test:
  commands:
    - openFPGALoader --help

about:
  home: https://github.com/trabucayre/openFPGALoader
  summary: 'Universal utility for programming FPGA'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timkpaine
