{% set version = "1.0.0" %}

package:
  name: openfpgaloader
  version: {{ version }}

source:
  url: https://github.com/trabucayre/openFPGALoader/archive/refs/tags/v{{ version }}.tar.gz
  sha256: cf19b596e5dea21891b1be3cb9a04be7a1501926ee0919dcc5c9f1b6d3bd0a96

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - pkg-config
    - cmake
    - make
  host:
    - zlib
    - libudev
    - libgpiod
    - libftdi
    - libusb
  run:
    - {{ pin_compatible("libudev") }}
    - {{ pin_compatible("libgpiod") }}
    - {{ pin_compatible("libftdi") }}

test:
  commands:
    - openFPGALoader --help

about:
  home: https://github.com/trabucayre/openFPGALoader
  summary: 'Universal utility for programming FPGA'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timkpaine
